### PR TITLE
Separate colored option with chat modes

### PR DESCRIPTION
**Pull request by AkazaRenn**
Two problems with this change:
1. Breaks settings file, I'm not familiar with the framework, not sure what can be done to fix it. What I did during testing was manually removing the settings file `%appdata%\XIVLauncher\pluginConfigs\PartyIcons.json`
2. Glowing job abbreviation is currently not available when colored is false, I'll check if it can be done later

The new settings look like this:
```json
{
  "$type": "PartyIcons.Configuration, PartyIcons",
  "ChatContentMessage": true,
  "HideLocalPlayerNameplate": true,
  "TestingMode": true,
  "EasternNamingConvention": false,
  "DisplayRoleInPartyList": false,
  "UseContextMenu": false,
  "AssignFromChat": true,
  "Version": 1,
  "IconSetId": 0,
  "SizeMode": 0,
  "NameplateOverworld": 2,
  "NameplateAllianceRaid": 5,
  "NameplateDungeon": 5,
  "NameplateBozjaParty": 5,
  "NameplateBozjaOthers": 0,
  "NameplateRaid": 6,
  "NameplateOthers": 2,
  "ChatOverworld": {
    "$type": "PartyIcons.View.ChatConfig, PartyIcons",
    "Mode": 2,
    "Colored": false
  },
  "ChatAllianceRaid": {
    "$type": "PartyIcons.View.ChatConfig, PartyIcons",
    "Mode": 2,
    "Colored": false
  },
  "ChatDungeon": {
    "$type": "PartyIcons.View.ChatConfig, PartyIcons",
    "Mode": 2,
    "Colored": false
  },
  "ChatRaid": {
    "$type": "PartyIcons.View.ChatConfig, PartyIcons",
    "Mode": 2,
    "Colored": false
  },
  "ChatOthers": {
    "$type": "PartyIcons.View.ChatConfig, PartyIcons",
    "Mode": 2,
    "Colored": false
  },
  "StaticAssignments": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[PartyIcons.Entities.RoleId, PartyIcons]], System.Private.CoreLib"
  }
}
```

### CODE REVIEW

**Comment by squidmade** [comment]
Letting you know due to personal things it's been a while but I do intend to get to this. I want to test this and then modify it in a way that will preserve existing settings if needed.

**Comment by AkazaRenn** [comment]
@squidmade No worries! Please take your time since this is all what I can do for now. I do appreciate your work!

**Comment by squidmade** [comment]
I made it so that the plugin can migrate settings from old to new versions (other refactoring got caught up when merging). More configurability is something that people have been requesting, so thank you for the PR.

**Comment by AkazaRenn** [comment]
> I made it so that the plugin can migrate settings from old to new versions (other refactoring got caught up when merging). More configurability is something that people have been requesting, so thank you for the PR.

Thank you so much for the work!

**Pull request merged**
