### PR TITLE
fixes to mentor icons and small mode

### PR DESCRIPTION
**Pull request by catgirlfighter**
Hope something will carry over.

### CODE REVIEW

**Comment by shdwp** [comment]
The diff got screwed up (nameplateview shows as completely rewritten) so it's pretty hard to even tell what that option does.

I might cherry pick one of the new profiles tho.

**Comment by catgirlfighter** [comment]
Yeah. Have now clue, why it happened. Tried to redo and it still shows like I've replaced the whole module. Maybe too many changes?

**Comment by catgirlfighter** [comment]
Resolved conflicts with new version. Broken diffs now look normal.

**Comment by catgirlfighter** [comment]
Small mode and job plates was added, so half of the pull doesn't make sense any more.
Closing this one, I'll make a new one later.

**Pull request closed without merging**
